### ISSUE TITLE
Check constraint as an expression instead of sql?

### ISSUE THREAD

**Issue by voroninp** [efcore/EFCore.CheckConstraints#143] opened 2023-12-29 11:12 UTC
I have two columns `StartDate` `EndDate`  and I'd like to express the constraint with the expression:
```
HasCheckContaint(entity => entity.StartDate < entity.EndDate);
```

Sure, I can do this just with a sql string, but then I need to specify the exact column names properties are mapped to.

**Comment by roji** [comment] 2023-12-29 13:17
Duplicate of https://github.com/dotnet/efcore/issues/11001

**Comment by roji** [comment] 2023-12-29 13:18
Note that this plugin (EFCore.CheckConstraints) is about automatically creating check constraints for you; if you'd like to define your own check constraints (regardless of whether you do that via SQL or an expression), then you're using EF directly and not this plugin.

**Closed by roji** 2023-12-29 13:18 UTC
