### ISSUE TITLE
"Invalid column name" exception during update-database

### ISSUE THREAD

**Issue by MelGrubb** [efcore/EFCore.CheckConstraints#16] opened 2020-12-16 17:01 UTC
I have a table-per-type hierarchy and added an enum value to a descendent class. The column is created on the descendent table, but the check constraint is being added to the base table in the resulting migrations, so SQL throws an error. I have similar constraints elsewhere, and they do not exhibit this behavior.

```
Applying migration '20201216161805_Initial migration'.
Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [dbo].[Activity] (
    [Id] bigint NOT NULL IDENTITY,
    [Description] nvarchar(1000) NULL,
    [Name] nvarchar(50) NOT NULL,
    CONSTRAINT [PK_Activity] PRIMARY KEY ([Id]),
    CONSTRAINT [CK_Exercise_ExerciseTypeId_Enum_Constraint] CHECK ([ExerciseTypeId] IN (0, 1, 2, 3)),
);

Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ExerciseTypeId'.
Invalid column name 'ExerciseTypeId'.
Invalid column name 'ExerciseTypeId'.
Invalid column name 'ExerciseTypeId'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:4958c8d0-4066-4eae-aa93-a220e1a0b4da
Error Number:207,State:1,Class:16
Invalid column name 'ExerciseTypeId'.
Invalid column name 'ExerciseTypeId'.
Invalid column name 'ExerciseTypeId'.
Invalid column name 'ExerciseTypeId'.
```
The description of the model has been simplified, but the relevant parts are still there.

In this case there is a base type called "Activity", and a derived type called "Exercise". Exercise has an ExerciseType property, which is an enumeration. The property is being generated on the proper table, but the constraint is being created on the base table.

**Comment by msawczyn** [comment] 2020-12-20 17:21
A minimalist repro for this bug is at https://github.com/msawczyn/EFCore.CheckConstraints/blob/main/EFCore.CheckConstraints.Test/TestUtilities/ConstraintsErrorExample.zip

**Comment by roji** [comment] 2021-03-10 22:00
Duplicate of https://github.com/dotnet/efcore/issues/24219

**Comment by roji** [comment] 2021-03-10 22:01
This is actually an EF Core issue that isn't related to this specific plugin - it's possible to reproduce the bug by manually adding a check constraint to the child entity.

**Closed by roji** 2021-03-10 22:01 UTC
